version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.64
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "spring-boot:16:1,micronaut:16:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kouncil:
    image: consdata/kouncil
    ports:
      - 8080:8080
    environment:
      bootstrapServers: "kafka:9092"
  micronaut:
    build:
      context: ./kafka-microframeworks-micronaut
    image: consdata/kafka-microframeworks-micronaut
    container_name: micronaut
  springboot:
    build:
      context: ./kafka-microframeworks-spring-boot
    image: consdata/kafka-microframeworks-spring-boot
    container_name: spring-boot
  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro