micronaut:
  application:
    name: kafka-microframeworks-micronaut
  server:
    port: 8082
  executors:
    consumer:
      type: fixed
      nThreads: 4

netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: kafka:9092
