server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      type: batch
    consumer:
      bootstrap-servers: kafka:9092
  cloud:
    stream:
      kafka:
        streams:
          binder:
            functions:
              merge:
                applicationId: spring-boot-kafka
      bindings:
        merge-in-0:
          destination: spring-boot-sell-orders
        merge-in-1:
          destination: spring-boot-buy-orders
